### ISSUE TITLE
'Portable' Installation?

### ISSUE THREAD

**Issue by paytah232** [nateobray/IPP#3]
Hi @nateobray, I'm not sure if I fully understand the implementation method here. I am trying to be able to print a PDF file or blob to my cups printer via ipp://.....

My hope is to make this code easily compatible on many devices but not installing anything to the system itself, and instead running everything purely on client side (php/js). Is there a way I can install and use your setup here by downloading certain files, and using include(files)/require(files) and be able to make it work?

Thanks in advance :)

**Comment by nateobray** [comment]
@paytah232, I don't think it would be impossible, but might be tricky.  

There's a couple layers here.  This libraries main purpose is to generate and encode, to the IPP specification, a payload that is then transmitted via an HTTP request.

When installed using composer, it will include other libraries I've created to generate a raw http request, and then connect and send that request to CUPS or directly to a printer (the later being the reason I wrote my own libraries,  as using curl or something similar doesn't work 100% of the time... but shouldn't be necessary with CUPS).  If you require/include all the files in this library (I know that's quite a few), it should work, provided you create your own IPPPayload and transmit via HTTP yourself.  I haven't tested using the library in this way, but happy to help if you can provide me with more details.

More specifically, what you would do is, if you look at `/obray/ipp/Printer->printJob()` function, you basically would use the library as it does there, right up to the final line where it does:
```return \obray\ipp\Request::send($this->printerURI, $encodedPayload, $this->user, $this->password);```
and instead use curl (or something) to to generate an http request to send your payload that's encoded in the line above (I believe with CUPS it works to just POST the `$encodedPayload`.

This library definitely needs some work still, to be super portable.  I use it where I work, to print million of documents per month in our warehousing and distribution centers, and it does that reliably enough.

It's not super clear to me what you're trying to do, but maybe this helps?

**Comment by paytah232** [comment]
Thank you for the super elaborate response. I will have to have a look into trying it (busy at the moment but it would be cool to have it work).

I've created my own website to generate product labels and print them. I was initially running python to print to cups which worked well on raspberry pi, but doesn't work well on my NAS. In order to make it more compatible (so I don't have to maintain two versions), I'm trying to make everything client side, so it will be compatible everywhere. Does that make sense? I think I found nodeJS is compatible on both, but still, it would be great to do everything client side.

**Comment by nateobray** [comment]
@Paytah232 , so by client are you saying, from the browser (assuming from javascript)?

I don't know if this would help, but they way I've done this is to setup a CUPS server connected to all my printers.  On that same CUPS server I installed PHP and used this library to create a "printing API".  Then from my client side app I'm just POSTing a base64 encoded document to my API endpoint.  The printing API receives the POSTed document, decodes the base64 encoded document, and using this library connects to the local CUPS server and submits the document for printing.  By creating the "printing API" I reduced the requirements of my front-end javascript app to just needing to post a base64 encoded document rather than needing to know anything about IPP or printing really at all.  That seemed simpler for my application.  

I maintain the print server as a separate project for my company, and we have deployed a bunch of them to the point where now I just have them as ubuntu images.  Obviously, the above only really works if you can have a centralized print server of some sort that you can install PHP on (and probably Nginx/apache too).

Otherwise I would look for someone that's created an IPP library for javascript, in which case you could send an IPP request directly to cups from your front-end javascript application.  I haven't looked if those exist or not.

This library, though should work too, if you really have PHP running on your "clients" as you suggest.  Still not sure I understand the setup very well, but probably just me.

**Comment by nateobray** [comment]
@Paytah232 , I'm closing the issue, but don't hesitate to reach out if you want to pursue this when you have more time.
